<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StaticDataController extends Controller
{
    public function getUnits()
    {
        $units = [
            ['label' => 'Square Metre', 'value' => 'M2'],
            ['label' => 'Can', 'value' => 'CA'],
            ['label' => 'Plate', 'value' => 'PG'],
            ['label' => 'Roll', 'value' => 'RO'],
            ['label' => 'Number', 'value' => 'NO'],
            ['label' => 'Barrel', 'value' => 'BLL'],
            ['label' => 'Packet', 'value' => 'PA'],
            ['label' => 'Cap', 'value' => 'AV'],
            ['label' => 'Kilometre', 'value' => 'KTM'],
            ['label' => 'Kilo-Gramme', 'value' => 'KG'],
            ['label' => 'Dozen', 'value' => 'DZ'],
            ['label' => 'Kilowatt', 'value' => 'KWT'],
            ['label' => 'Part per Thousand', 'value' => 'NX'],
            ['label' => 'Bag', 'value' => 'BG'],
            ['label' => 'Pound', 'value' => 'LBR'],
            ['label' => 'Pieces/Item', 'value' => 'U'],
            ['label' => 'Drum', 'value' => 'DR'],
            ['label' => 'Pair', 'value' => '4B'],
            ['label' => 'Carat', 'value' => 'CR'],
            ['label' => 'Tube', 'value' => 'TU'],
            ['label' => 'Box', 'value' => 'BX'],
            ['label' => 'Set', 'value' => 'SET'],
            ['label' => 'Metre', 'value' => 'MTR'],
            ['label' => 'Gram', 'value' => 'GRM'],
            ['label' => 'Gallon', 'value' => 'GLL'],
            ['label' => 'Cell', 'value' => 'CEL'],
            ['label' => 'Block', 'value' => 'BL'],
            ['label' => 'Megawatt Hour', 'value' => 'MWT'],
            ['label' => 'Bundle', 'value' => 'BE'],
            ['label' => 'Yard', 'value' => 'YRD'],
            ['label' => 'Cubic Metre', 'value' => 'M3'],
            ['label' => 'Litre', 'value' => 'L'],
            ['label' => 'Milligram', 'value' => 'MGM'],
            ['label' => 'Tonne', 'value' => 'TNE'],
            ['label' => 'Gross', 'value' => 'GRO'],
            ['label' => 'Sheet', 'value' => 'ST'],
            ['label' => 'Link', 'value' => 'LK'],
            ['label' => 'Centimetre', 'value' => 'CMT'],
            ['label' => 'Reel', 'value' => 'RL'],
        ];

        return response()->json($units);
    }

    public function getCategories()
    {
        $categories = [
            "Minerals and Supplements",
            "Equipment",
            "Veterinary Products",
            "Hygiene",
            "Seeds",
            "Feeds",
            "Agrochemicals",
            "Fertilizers",
            "Insecticide",
            "Public Health",
            "Animal feeds",
            "Services",
            "Herbicide",
            "Sanitation",
            "Maize",
            "Drinks",
            "Fertilizer"
        ];
        return response()->json($categories);
    }

    public function getManufacturers()
    {
        $manufacturers=[
            "Vital Animal Health",
            "Bimeda Ltd.",
            "East African Seed Company Ltd.",
            "Elgon Kenya Ltd.",
            "HighChem Essentials Ltd.",
            "Kenya Seed Company Ltd.",
            "Norbrook Kenya Ltd.",
            "Orbit Chemical Industries Ltd.",
            "Osho Chemical Industries Ltd.",
            "Pannar Seed K. Ltd.",
            "Syngenta",
            "Twiga Chemical Industries Ltd.",
            "Ultravetis East Africa Ltd.",
            "Wonder Feeds Ltd.",
            "Vetcare Africa",
            "Tosha Product (K) Ltd.",
            "Turbo Feeds - Limuru Posho Mills Ltd.",
            "Pecolchem Enterprises",
            "Agrichem Africa Ltd.",
            "Juanco SPS Ltd.",
            "Hygrotech E A Ltd.",
            "Bayer East Africa Ltd.",
            "Eldoret Holdings Co Ltd.",
            "Master Ani Feeds (K) Ltd.",
            "Medilink Labs & Surgicals Ltd.",
            "Eagle Vet Kenya Ltd.",
            "Hangzhou Agrochemical E.A. Ltd.",
            "VetAgro Ltd.",
            "Pwani Feeds Ltd.",
            "Pembe Flour Mills Ltd.",
            "Murphy Chemicals (E.A.) Ltd.",
            "Excel Crop Care Ltd.",
            "Biodeal Laboratories Ltd.",
            "Cooper K-Brands Ltd.",
            "Kaluworks Ltd.",
            "Simlaw Seeds Company Ltd.",
            "Unga Farmcare (EA) Ltd.",
            "Bidco Land O'Lakes",
            "Kenya Highland Seed Co. Ltd.",
            "Amiran K. Ltd.",
            "Tarime Suppliers Ltd.",
            "Pioneer Feeds Ltd.",
            "ARM Cement Ltd.",
            "Arysta LifeScience Kenya Ltd.",
            "Ecofeed Enterprises",
            "Joyline East African Ltd.",
            "MolaPlus Ltd.",
            "Cosmos Ltd.",
            "Medisel (K) Ltd.",
            "Export Trading Group",
            "Agri Seed Co Ltd.",
            "CFAO Kenya Ltd.",
            "EuroChem International Ltd.",
            "GreenLife Crop Protection Africa",
            "Agro-solutions Ltd.",
            "SoilCares Africa",
            "Kenagro Suppliers Ltd.",
            "Dryland Seed Ltd.",
            "Nerix Pharma Ltd.",
            "Jolichem Suppliers Ltd.",
            "Medina Chemicals Ltd.",
            "Aesthetics Ltd.",
            "Adenchem Stores Ltd.",
            "Zoetis South Africa (Pty) Ltd.",
            "Farm Feeds Ltd.",
            "Alpha Medical Manufacturers Ltd.",
            "Quality Logistics Ltd.",
            "Zelena Grow Ltd.",
            "Kenya Agricultural & Livestock Research Organization",
            "Dudu East Africa",
            "Nutrifarm",
            "HM.Clause Kenya Ltd.",
            "Yara East Africa Ltd.",
            "Safari Seeds Ltd.",
            "Metrovet Kenya Ltd.",
            "Maisha Minerals & Fertilizers Ltd.",
            "Acme Containers Ltd.",
            "Daps Distribution Co. Ltd.",
            "Rhino Seeds Africa Ltd.",
            "Royal Seed",
            "Pearl Seeds Ltd.",
            "Bukoola Chemicals Industries Ltd.",
            "Golden Harvest Mills",
            "Heritage Foods Kenya Ltd.",
            "VetPro Ltd.",
            "Grainpulse Ltd.",
            "Jubaili Agrotec Ltd.",
            "Lentera Africa",
            "Fanisi Fertilizer",
            "PZ Cussons",
            "Interagro (K) Ltd.",
            "Purti Agrotech Ltd.",
            "Novixa International Ltd.",
            "Farmfix Africa Co. Ltd.",
            "Truvets Techno-Systems Ltd.",
            "Advanta Seed International",
            "New Kenya Seeds Ltd",
            "Wetlife bottlers Ltd.",
            "Kim-Fay East Africa Ltd.",
            "Western Seed Company Limited",
            "OCP Kenya Ltd.",
            "Mea Ltd.",
            "Nairobi veterinary Centre",
            "Nevas Vet Agro-Suppliers",
            "Supreme Farmcare Supplies",
            "GLENERGY (K) LTD.",
            "Doshi Group Company Ltd.",
            "Monsanto Kenya Ltd.",
            "Hemco Designs Ltd.",
            "Elite K. Ltd.",
            "Bakex Millers Ltd.",
            "Economy Farm Products (K) Ltd.",
            "Cafaech Enterprises",
            "Tagros Chemicals India Ltd.",
            "Tata Chemicals Ltd.",
            "Green Live Ltd.",
            "Dow AgroSciences UK Ltd.",
            "R.H. Devani Ltd.",
            "Wellstock",
            "A to Z Textile Mills Ltd.",
            "Ashish Life Science Pvt Ltd.",
            "Shamika Enterprises Ltd.",
            "Pioneer Hi-Bred Kenya Ltd.",
            "Sidai Africa Ltd.",
            "Kapi Ltd.",
            "Supplies and Services Ltd.",
            "Minjingu Mines & Fertilizer Ltd.",
            "Greenspec Ltd.",
            "Continental Seeds",
            "Supreme",
            "Purdue Agriculture",
            "Farmate ltd.",
            "Bell Industries Ltd.",
            "Mazao na Afya",
            "Global Nutrition Solutions",
            "New Manufacturer",
            "Afcott Ventures Kenya Ltd",
            "Medivet",
            "EAGLE CHEMICALS KENYA LIMITED",
            "Kitale Industries Limited",
            "Sanergy",
            "SHREE AGRO AFRICA LIMITED",
            "iProcure Limited",
            "Mombasa Maize Millers",
            "GoK National Subsidy"
        ];
          
        return response() -> json($manufacturers);
    }
}
