<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StaticDataController extends Controller
{
    public function getUnits()
    {
        $units = [
            ['label' => 'Square Metre', 'value' => 'M2'],
            ['label' => 'Can', 'value' => 'CA'],
            ['label' => 'Plate', 'value' => 'PG'],
            ['label' => 'Roll', 'value' => 'RO'],
            ['label' => 'Number', 'value' => 'NO'],
            ['label' => 'Barrel', 'value' => 'BLL'],
            ['label' => 'Packet', 'value' => 'PA'],
            ['label' => 'Cap', 'value' => 'AV'],
            ['label' => 'Kilometre', 'value' => 'KTM'],
            ['label' => 'Kilo-Gramme', 'value' => 'KG'],
            ['label' => 'Dozen', 'value' => 'DZ'],
            ['label' => 'Kilowatt', 'value' => 'KWT'],
            ['label' => 'Part per Thousand', 'value' => 'NX'],
            ['label' => 'Bag', 'value' => 'BG'],
            ['label' => 'Pound', 'value' => 'LBR'],
            ['label' => 'Pieces/Item', 'value' => 'U'],
            ['label' => 'Drum', 'value' => 'DR'],
            ['label' => 'Pair', 'value' => '4B'],
            ['label' => 'Carat', 'value' => 'CR'],
            ['label' => 'Tube', 'value' => 'TU'],
            ['label' => 'Box', 'value' => 'BX'],
            ['label' => 'Set', 'value' => 'SET'],
            ['label' => 'Metre', 'value' => 'MTR'],
            ['label' => 'Gram', 'value' => 'GRM'],
            ['label' => 'Gallon', 'value' => 'GLL'],
            ['label' => 'Cell', 'value' => 'CEL'],
            ['label' => 'Block', 'value' => 'BL'],
            ['label' => 'Megawatt Hour', 'value' => 'MWT'],
            ['label' => 'Bundle', 'value' => 'BE'],
            ['label' => 'Yard', 'value' => 'YRD'],
            ['label' => 'Cubic Metre', 'value' => 'M3'],
            ['label' => 'Litre', 'value' => 'L'],
            ['label' => 'Milligram', 'value' => 'MGM'],
            ['label' => 'Tonne', 'value' => 'TNE'],
            ['label' => 'Gross', 'value' => 'GRO'],
            ['label' => 'Sheet', 'value' => 'ST'],
            ['label' => 'Link', 'value' => 'LK'],
            ['label' => 'Centimetre', 'value' => 'CMT'],
            ['label' => 'Reel', 'value' => 'RL'],
        ];

        return response()->json($units);
    }

    public function getCategories()
    {
        $categories = [
            "Minerals and Supplements",
            "Equipment",
            "Veterinary Products",
            "Hygiene",
            "Seeds",
            "Feeds",
            "Agrochemicals",
            "Fertilizers",
            "Insecticide",
            "Public Health",
            "Animal feeds",
            "Services",
            "Herbicide",
            "Sanitation",
            "Maize",
            "Drinks",
            "Fertilizer"
        ];
        return response()->json($categories);
    }

    public function getManufacturers()
    {
        $manufacturers=[
            "Acme Containers Ltd.",
            "Adenchem Stores Ltd.",
            "Aesthetics Ltd.",
            "Advanta Seed International",
            "Afcott Ventures Kenya Ltd",
            "Alpha Medical Manufacturers Ltd.",
            "A to Z Textile Mills Ltd.",
            "Agrichem Africa Ltd.",
            "Agri Seed Co Ltd.",
            "Agro-solutions Ltd.",
            "Amiran K. Ltd.",
            "Ashish Life Science Pvt Ltd.",
            "Bayer East Africa Ltd.",
            "Bell Industries Ltd.",
            "Bidco Land O'Lakes",
            "Bimeda Ltd.",
            "Biodeal Laboratories Ltd.",
            "Bakex Millers Ltd.",
            "Cafaech Enterprises",
            "Continental Seeds",
            "Cooper K-Brands Ltd.",
            "Daps Distribution Co. Ltd.",
            "Doshi Group Company Ltd.",
            "Dow AgroSciences UK Ltd.",
            "Dudu East Africa",
            "Dryland Seed Ltd.",
            "East African Seed Company Ltd.",
            "Eagle Vet Kenya Ltd.",
            "EAGLE CHEMICALS KENYA LIMITED",
            "Elite K. Ltd.",
            "Economy Farm Products (K) Ltd.",
            "Ecofeed Enterprises",
            "Eldoret Holdings Co Ltd.",
            "Excel Crop Care Ltd.",
            "EuroChem International Ltd.",
            "Fanisi Fertilizer",
            "Farm Feeds Ltd.",
            "Farmate ltd.",
            "Farmfix Africa Co. Ltd.",
            "GLENERGY (K) LTD.",
            "Global Nutrition Solutions",
            "Golden Harvest Mills",
            "Green Live Ltd.",
            "GreenLife Crop Protection Africa",
            "Greenspec Ltd.",
            "Hangzhou Agrochemical E.A. Ltd.",
            "Heritage Foods Kenya Ltd.",
            "HighChem Essentials Ltd.",
            "HM.Clause Kenya Ltd.",
            "Interagro (K) Ltd.",
            "iProcure Limited",
            "Juanco SPS Ltd.",
            "Jolichem Suppliers Ltd.",
            "Joyline East African Ltd.",
            "Jubaili Agrotec Ltd.",
            "Kaluworks Ltd.",
            "Kapi Ltd.",
            "Kenagro Suppliers Ltd.",
            "Kenya Agricultural & Livestock Research Organization",
            "Kenya Highland Seed Co. Ltd.",
            "Kenya Seed Company Ltd.",
            "Kim-Fay East Africa Ltd.",
            "Kitale Industries Limited",
            "Lentera Africa",
            "Maisha Minerals & Fertilizers Ltd.",
            "Medilink Labs & Surgicals Ltd.",
            "Medisel (K) Ltd.",
            "Medina Chemicals Ltd.",
            "Medivet",
            "Mea Ltd.",
            "Mombasa Maize Millers",
            "Master Ani Feeds (K) Ltd.",
            "Monsanto Kenya Ltd.",
            "Murphy Chemicals (E.A.) Ltd.",
            "MolaPlus Ltd.",
            "Metrovet Kenya Ltd.",
            "Nairobi veterinary Centre",
            "Nevas Vet Agro-Suppliers",
            "New Kenya Seeds Ltd",
            "New Manufacturer",
            "Nerix Pharma Ltd.",
            "Nutrifarm",
            "OCP Kenya Ltd.",
            "Orbit Chemical Industries Ltd.",
            "Osho Chemical Industries Ltd.",
            "Pannar Seed K. Ltd.",
            "Pembe Flour Mills Ltd.",
            "Pearl Seeds Ltd.",
            "Pioneer Feeds Ltd.",
            "Pioneer Hi-Bred Kenya Ltd.",
            "PZ Cussons",
            "Pwani Feeds Ltd.",
            "Purti Agrotech Ltd.",
            "Purdue Agriculture",
            "Rhino Seeds Africa Ltd.",
            "R.H. Devani Ltd.",
            "Royal Seed",
            "Safari Seeds Ltd.",
            "Sanergy",
            "Shamika Enterprises Ltd.",
            "Sidai Africa Ltd.",
            "Supreme Farmcare Supplies",
            "Supreme",
            "Tagros Chemicals India Ltd.",
            "Tata Chemicals Ltd.",
            "Tarime Suppliers Ltd.",
            "Tosha Product (K) Ltd.",
            "Truvets Techno-Systems Ltd.",
            "Turbo Feeds - Limuru Posho Mills Ltd.",
            "Twiga Chemical Industries Ltd.",
            "Ultravetis East Africa Ltd.",
            "Unga Farmcare (EA) Ltd.",
            "VetAgro Ltd.",
            "Vetcare Africa",
            "VetPro Ltd.",
            "Vital Animal Health",
            "Wellstock",
            "Western Seed Company Limited",
            "Wonder Feeds Ltd.",
            "Yara East Africa Ltd.",
            "Zoetis South Africa (Pty) Ltd.",
            "Zelena Grow Ltd."
        ];
          
        return response() -> json($manufacturers);
    }
}
